### ISSUE TITLE
fails to build with ghc-9.10

### ISSUE THREAD

**Issue by juhp** [AshleyYakeley/witness#2]
For Stackage Nightly with ghc-9.10.1:

```
       Configuring witness-0.6.2...
       Preprocessing library for witness-0.6.2...
       Building library for witness-0.6.2...
       [ 1 of 34] Compiling Import
       [ 2 of 34] Compiling Data.Type.Witness.General.WitnessConstraint
       [ 3 of 34] Compiling Data.Type.Witness.General.TestHetEquality
       [ 4 of 34] Compiling Data.Type.Witness.General.Order
       [ 5 of 34] Compiling Data.Type.Witness.General.HetConstraint
       [ 6 of 34] Compiling Data.Type.Witness.General.AllConstraint
       [ 7 of 34] Compiling Data.Type.Witness.Specific.Some
       /home/curators/work/unpack-dir/unpacked/witness-0.6.2-33790bc5ba957951993960a3388d72d82a38ac7cb64181f0ec2a7d6f9a48849a/src/Da
ta/Type/Witness/Specific/Some.hs:53:13: error: [GHC-83865]
           • Expected kind ‘forall k. (k -> Type) -> Type’,
               but ‘SomeFor (Const ())’ has kind ‘(k0 -> Type) -> Type’
           • In the type ‘SomeFor (Const ())’
             In the type declaration for ‘Some’
          |
       53 | type Some = SomeFor (Const ())
          |             ^^^^^^^^^^^^^^^^^^
        
       [19 of 34] Compiling Data.Type.Witness.Apply
       [20 of 34] Compiling Data.PeanoNat
```

**Comment by AshleyYakeley** [comment]
Fixed in witness-0.4.
